name: iOS Build
on: 
  push:
    paths-ignore:
    - 'android/**'
    - 'apidoc/**'
  pull_request:
    paths-ignore:
    - 'android/**'
    - 'apidoc/**'
  workflow_dispatch:
  
jobs:
  ios:
    runs-on: macos-latest
    name: iOS
    steps:
    - uses: actions/checkout@v2

    - name: Retrieve package version
      run: |
        PACKAGE_VERSION=$(sed -n 's/^ *"version": *"//p' package.json | tr -d '"' | tr -d ',' | tr -d '[[:space:]]')
        echo "packageVersion=${PACKAGE_VERSION}" >> $GITHUB_ENV

    - name: Test Native Code
      working-directory: ./iphone
      run: xcodebuild -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12' -scheme hyperloop -target Tests -configuration Debug GCC_PREPROCESSOR_DEFINITIONS='USE_JSCORE_FRAMEWORK=1' test | xcpretty -r junit

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Package metabase
      working-directory: ./packages/hyperloop-ios-metabase
      run: |
        npm pack
        METABASE_VERSION=$(sed -n 's/^ *"version": *"//p' package.json | tr -d '"' | tr -d ',' | tr -d '[[:space:]]')
        echo "METABASE_VERSION=${METABASE_VERSION}" >> $GITHUB_ENV

    - name: Prepare hook
      working-directory: ./iphone/hooks
      run: |
        npm i --production
        npm i ../../packages/hyperloop-ios-metabase/hyperloop-metabase-${{ env.METABASE_VERSION }}.tgz
        rm -rf node_modules/findit/test
        rm -rf package-lock.json

    - run: npm i -g titanium
      name: Install Titanium CLI

# TODO cache SDK install

    - run: ti sdk install 9.3.2.GA --force
      name: Install SDK 9.3.2.GA

    - run: sed -i .bak 's/TITANIUM_SDK_VERSION = .*/TITANIUM_SDK_VERSION = 9.3.2.GA/' iphone/titanium.xcconfig
      name: Set to Build with 9.3.2.GA SDK

    - name: Build
      working-directory: ./iphone
      run: ti build -p ios --build-only

    - name: Archive iOS artifact
      uses: actions/upload-artifact@v2
      with:
        name: hyperloop-iphone-${{ env.packageVersion }}
        path: |
          ios/dist/hyperloop-iphone-*.zip
